### ISSUE TITLE
Vietnam War Flags

### ISSUE THREAD

**Issue by agisXIV** [zond/godip#100]
I've made a collection of all the flags needed for the variant, they are all in the public domain, so I just got them from Wikimedia. I wasn't able to fork a file upload, so I thought I would just put them here:

[Vietnam_War_Flags.zip](https://github.com/zond/godip/files/4866802/Vietnam_War_Flags.zip)

**Comment by tttppp** [comment]
Thanks!  The tricky thing with flags is making them look nice as squares.  If you could edit these to be squares then I should be able to put them live fairly quickly.

**Comment by agisXIV** [comment]
[VietnamSquareFlags.zip](https://github.com/zond/godip/files/4978150/VietnamSquareFlags.zip)

Better?

**Comment by tttppp** [comment]
This is brilliant - thanks. I've put this live now.
