### ISSUE TITLE
Difference between Dislodgeds and Dislodgers

### ISSUE THREAD

**Issue by Wulfheart** [zond/godip#111]
``POST http://godip-adjudication.appspot.com/{variant name}`` returns two keys which are unclear to me. Even after looking up the godoc.
What is the difference between ``Dislodgeds`` and ``Dislodgers``?

**Comment by zond** [comment]
When a unit dislodges another unit, it is a dislodger. When a unit gets dislodged by another unit, it is a dislodged unit. Does that explanation make sense? :)

**Comment by Wulfheart** [comment]
Yes thanks. However what could the info that a unit is dislodging another unit be used as?

**Comment by zond** [comment]
When rendering them, maybe? This is just a library, what you use the results for is up to you :)
