### ISSUE TITLE
Unable to open map svg

### ISSUE THREAD

**Issue by Wulfheart** [zond/godip#116]
When trying to open the svg in inkscape I'm getting an error that it is not possible to open the file. I'm using Inkscape 1.0.1 on Windows 10.
Is this behaviour expected due to some edits or not?

**Comment by zond** [comment]
@tttppp Is this something you recognize?

**Comment by JorenC** [comment]
Which map? Classical map.svg?

**Comment by Wulfheart** [comment]
@JorenC Sorry for not mentioning it. Yes, classical map.

**Comment by Wulfheart** [comment]
After deleting the style tags with webfonts it worked fine. However this is an issue which should be investigated further.

**Comment by JorenC** [comment]
I'm not sure - I think this is an inkscape issue, maybe. 

Note that the webfonts are added in the script AFTER the map is finalized - it's the only safe way to ensure the map will display correctly in all clients...

**Comment by tttppp** [comment]
It opens for me fine in Inkscape.  I'm not on Windows though. Do you get this issue with any of the other maps?  In particular I think Ancient Med has an embedded font too (for most of the others I don't think we bothered).
