### ISSUE TITLE
Determining render position of units in map

### ISSUE THREAD

**Issue by Wulfheart** [zond/godip#117]
![grafik](https://user-images.githubusercontent.com/25671390/99907153-74903580-2cdb-11eb-8527-78ae259a0fe9.png)

Given the provided map. How can I determine the position of a unit? Is there any layer that I'm not aware of yet which is responsible for the unit positions?

**Comment by zond** [comment]
Yes, the SCs are marked by black dots (on most maps) having element names matching the SC names. Unfortunately the algorithm is still naive, primitive, and based on how Droidippy did it back when there was only a single variant: Pick the start pos of the path of the SC dot, and offset it a fixed number for armies, and another for fleets.

**Comment by zond** [comment]
It would be fairly simple to add a variant struct field containing the offset required for each unit type, of course.

**Comment by zond** [comment]
I forgot to mention: Non SCs also have those paths, but invisibly.
