### ISSUE TITLE
Discussion: Beta releases of variants

### ISSUE THREAD

**Issue by tttppp** [zond/godip#12]
It seems likely that when new variants are released they will have bugs in them.  The obvious solution to this is to do more testing.  I could definitely have done more local testing before pushing a MR for Pure, in particular by using the localhost mode in the Android client. However I think more complex variants are likely to have bugs that are only found during actual play. Is it worth the development effort to add some sort of beta testing mode?

I think the main feature of this mode should be simply that the user is warned the variant is in beta and so may not work as expected. However it might be good to exclude beta games from stats too.

Another option would be to have a user variable for whether they want to see variants that are in beta or not. This sounds like it would be more work.

**Comment by zond** [comment]
I vote for just having a beta flag that makes them unrated and warns about them.

**Comment by tttppp** [comment]
And a code change to move variants out of beta? I'm only about 70% in favour of implementing this idea at all. Part of me thinks that devs should just test their code better! :-)

One thing I want to make is a script that creates a set of SVGs for any input map showing a unit on each province, arrows between each connected province, stripes on every province, etc. Manual inspection of the output would have caught the issues with the Pure map.

**Comment by tttppp** [comment]
I agree that the second option (opt in for beta maps) is overkill for this.

**Comment by zond** [comment]
Lets let it rest a while and think some more then :)

**Comment by zond** [comment]
Though the test script sounds useful! Maybe add an endpoint to the variants directory that just renders random units and orders?

**Comment by tttppp** [comment]
I'm going to close this as I think the test script allows an easy way to check map files are created roughly right. I'm not against having some special handling for beta maps, but I'm not planning on adding it any time soon.
