### ISSUE TITLE
Create Ancient Mediterranean Variant

### ISSUE THREAD

**Issue by tttppp** [zond/godip#14]
This is a five player game on a custom map. The full rules are [here](http://www.dipwiki.com/?title=Ancient_Mediterranean) and they are the same as the base game, but with a different adjacency.  I wanted to implement this because it's a different map, a different number of players and because it's gets [played quite a lot](http://vdiplomacy.net/variants.php?).

I am planning to make Baleares a non-convoy space as is done [here](http://webdiplomacy.net/variants.php#AncMed).

I have started on the map, and it currently looks like this:

![ancientmediterraneanmap svg_1](https://user-images.githubusercontent.com/7073263/27153539-c4569d14-5149-11e7-8cda-4697441f9ea6.png)

It needs more work to make canals clearer, and I haven't created the province layer yet.  Any suggestions welcome, although I can't promise I'll do them as creating the map is (as expected) time consuming!

**Comment by zond** [comment]
Very cool! It all sounds good to me.

I'll be happy to talk about potentially necessary code changes to handle variant particulars :)
