### ISSUE TITLE
Renaissance Variant

### ISSUE THREAD

**Issue by redbhoy** [zond/godip#15]
Hi! I'm new to all of this but I reckon I might be able to build variants too. Can someone please let me know which files I have to modify and also give me a little bit of map help? There might be a bit of chat back and forth until I sort everything out (I'm not a programmer, but I'm reasonably literate). I want to start with something very easy to understand it, so I'd like to do Renaissance, but which is pretty much standard map with new powers and home SCs. Also a passable SC in Switzerland. Thanks for any help you can provide.

**Comment by zond** [comment]
Look at the Pure pull requests, in particular https://github.com/zond/godip/pull/5 I guess, tp get a sense for what's needed for a variant that changes nothing more complex than the map.

Also, @tttppp may have advice.

**Comment by redbhoy** [comment]
I've recoded the map parts - can I access the svg file for the standard map
somewhere? Sorry for the noob questions, but once I know where things are
kept I'll be able to hopefully contribute!

**Comment by tttppp** [comment]
The Classical map is here: https://github.com/zond/godip/tree/master/variants/classical/svg

Once you've made your new version then you need to run a script called go-bindata to convert it to an asset file. If you struggle with that step then it might be easier just to push the svg and I can run the conversion script for you.

There are details about the svg map format on the readme page for the project.

Also feel free to ask if you have questions on how to use git to get your changes onto the github site.

**Comment by tttppp** [comment]
You will need to override the BlankStart and Nations fields to set the start year and nations respectively. Have a look at the file classical.go for details of how these are set (you may also need to look at the common.go in the classical/common directory).

**Comment by tttppp** [comment]
One other thing: since the Pure variant was added we also added meta data about the variants (creator, rules, etc). These will need adding too: https://github.com/zond/godip/pull/9/files

**Comment by zond** [comment]
Also, @tttppp, you ought to join https://groups.google.com/forum/#!forum/diplicity-dev so we can communicate easier :)

**Comment by tttppp** [comment]
Ok, I've joined. It looks like there's not been much there for a while (since 2015?)

**Comment by zond** [comment]
True, but lets liven it up!

**Comment by tttppp** [comment]
I don't know how far this got, but it looks fairly quick to implement. The slow bit will be play testing, but we now have a working beta program. @redbhoy Are you still interested in finishing this? Do you need any help with the svg manipulation?

If you push what you have so far to a branch then I should be able to help you finish it off.

**Comment by JorenC** [comment]
@tttppp shall we close this issue?

**Comment by tttppp** [comment]
Yes, I think it's fair to close this now. Happy to reopen if there is a desire to continue though.
