### ISSUE TITLE
Adjudicate from Serialized Data?

### ISSUE THREAD

**Issue by NSinopoli** [zond/godip#2]
Hi there,

After much research of other open-source Diplomacy adjudicators, I'm most impressed with the quality of your library. DATC-compliance, discovery of issues with the original [Kruijswijk algorithm](http://diplom.org/Zine/F2013R/Bruse/adjudicator.htm), and tested against over 5000 real games... incredible work. Really.

I'd love to use your library, but I'm not familiar with Go. Is there any chance godip could accept serialized data (preferably JSON), adjudicate accordingly, and then return a serialized response?

Thanks again for all of your exhaustive work on this project!

**Comment by zond** [comment]
Thank you for your kind words!

A few notes:

- Go is incredibly easy to learn. I don't know a single programmer who
isn't productive in Go after 10-30 hours.

- Go can be compiled to .dll or .so files and linked against add if they
were regular dynamic libraries. This lets you link C, C++, Java, Ruby,
Python or basically almost anything against a Go library. See
http://blog.ralch.com/tutorial/golang-sharing-libraries/ for example.

- Go can be transpiled to JavaScript, and
https://github.com/spamguy/diplomacy-godip has done just that woth godip.

- Writing a small service that just accept JSON, adjudicates it and
responds with the results should be pretty simple if you use godip.

Good luck!

On Mar 7, 2016 18:53, "Nick Sinopoli" <notifications@github.com> wrote:
>
> Hi there,
>
> After much research of other open-source Diplomacy adjudicators, I'm most
impressed with the quality of your library. DATC-compliance, discovery of
issues with the original Kruijswijk algorithm, and tested against over 5000
real games... incredible work. Really.
>
> I'd love to use your library, but I'm not familiar with Go. Is there any
chance godip could accept serialized data (preferably JSON), adjudicate
accordingly, and then return a serialized response?

**Comment by NSinopoli** [comment]
Thank you, this is an excellent start! I'll post back here if/when I'm able to repurpose your library.

**Comment by zond** [comment]
Great!
