### ISSUE TITLE
Suggested support option from STP/NC to LVN

### ISSUE THREAD

**Issue by tttppp** [zond/godip#20]
I've pushed a test case for this to the [CoastalSupportOption](https://github.com/zond/godip/tree/CoastalSupportOption) branch.  I noticed this yesterday and hoped it might be fixed with the same change as #19. 

Trying to carry out this support move raises an InternalServerError in the app, so there's not really an much of an issue here. 

(This is a complete edge case)

**Comment by zond** [comment]
Look at 6.B.4. TEST CASE, SUPPORT TO UNREACHABLE COAST ALLOWED in http://web.inter.nl.net/users/L.B.Kruijswijk/#6.B, that support should actually be allowed...

**Comment by tttppp** [comment]
No, that's different. This is a unit supporting a fleet to make an invalid move. Moscow can move to both St Petersburg and Livonia, but St Petersburg  (North) can't move to Livonia.

The server correctly rejects the support order, but it shouldn't really suggest it in the first place.

**Comment by tttppp** [comment]
In particular the order "Army Moscow support Fleet St Petersburg to Livonia" should only be advertised if the fleet is on the South coast.

**Comment by zond** [comment]
Ah, I see. Yeah, supporting that move shouldn't be suggested...
