### ISSUE TITLE
SVG variant naming conventions

### ISSUE THREAD

**Issue by spamguy** [zond/godip#23]
Third party clients (_e.g. dipl.io)_ should be able to more easily customise SVG maps generated by Godip. There is no consistent ID naming convention in place for elements and their groups, so I can't guarantee that customisations that work in one variant's map will work in another.

**Example use case:** I'm not fond of the unit shapes and would rather override them with my own. My approach would be to select `<g id="units"></g>`, calculate the bounding box of each child element, and use the results to insert a new path element. There is no group of ID 'units', and I'm not sure if I can query by 'inkscape:label=units'.

**Work involved:** IDs would need to be explicitly and consistently set across all variant SVG files. Groups would receive predictable names like 'units', 'supplyCentres', 'provinces', whilst respective child elements would be named 'sevUnit', 'sevSC', 'sev', something like those.

**Comment by spamguy** [comment]
Alternatively, create an API endpoint that dispenses SVG metadata for a supplied variant, similar to dipl.io's variant definition files.

**Comment by zond** [comment]
Both solutions seem fine to me.

You are welcome to provide patches to implement either one.

Maybe the SVG convention solution is easiest for you, since it doesn't
require much familiarity with the server code.

In case you want to implement that one, just also add to the README about
map creation :)

**Comment by spamguy** [comment]
Before I attempt something like this, what are the risks to android-diplicity? I expect only to be messing with IDs.

**Comment by zond** [comment]
I believe the only code using the IDs is in https://github.com/zond/diplicity/blob/master/app/js/dippymap.js, right @tttppp ?

**Comment by zond** [comment]
I think that you can basically add any IDs you want. Any IDs that the current code cares about is already standardized to be the same in all maps.

**Comment by tttppp** [comment]
So, exactly what zond said. The ids that need to be standardised are already set. The README for this project contains information about how the ids should be set.

For the example you mentioned about units, the README already says:
Units layer (with id="units"): This will be empty in the map file.
So if any maps just have the inkscape layer name set then please feel free to set the id too.

We should document the updated standard in the README file.

I'm currently in the process of trying to write a script to make creating map-only variants easier. I'll include any new layer ids in it.

**Comment by spamguy** [comment]
Do I need to be added as a contributor to this repo? I tried pushing a branch here but was denied access.

The ticket can be assigned to me as well.

**Comment by zond** [comment]
Just fork it and create a pull request, that's the easiest way :)

**Comment by spamguy** [comment]
Resolved.
