### ISSUE TITLE
Hundred Variant

### ISSUE THREAD

**Issue by tttppp** [zond/godip#26]
Support for the three player Hundred variant: http://www.variantbank.org/results/rules/h/hundred.htm

This is basically a map-only variant, except for the following:
* Build anywhere. This is a very common variant rule, and so it would be good to ensure we support it.
* Years increase in fives. No idea if this will be trivial or annoying to implement!  I'm sure it can't be that hard.
* France starts with a unit not in a supply center (and fewer centers than units).
* There's an optional rule for Fleet English Channel (which I don't intend to implement).

The variant is pretty popular and seems surprisingly well balanced: http://www.vdiplomacy.com/stats.php?variantID=8

**Comment by zond** [comment]
Build anywhere requires code changes. Maybe a new build order that doesn't validate home-ness of the SC is the simplest way? It could possibly be implemented similarly to how move-via-convoy is implemented (with a flag for "build anywhere" in the build order). If the `DisplayType` of the new order is to be the same as the old build order the parse funcs need to be changed too to create build orders with the "build anywhere" flag set.

Year increase can be added pretty easily with a new Phase implementation that just "subclasses" (the Go way, by containing an anon Classical phase inside) and replaces `Prev` and `Next` with something that moves five years instead.

The positioning and numbers are just start states, and doesn't need code changes per se.

The channel rule is actually very simple to implement! Just add edges between lon and cal that both armies and fleets can move along and you should be golden.

**Comment by tttppp** [comment]
Build anywhere is much more of a pain than I assumed. The DSL already allowed for multiple Conn calls and so I'd assumed I could make a variant "build anywhere" by just writing:
```
Prov(...)....SC(England).SC(Burgundy).SC(France)
```
Unfortunately this results in England and Burgundy having no home centres, and France owning all of them.

Consequently I might switch to implementing an easier variant for the first pass of the variant generator, but I think this would be good to do too.

**Comment by zond** [comment]
Yeah, as I said :) "Build anywhere" needs some changes, and the simplest way is probably a new order type...
