### ISSUE TITLE
Cold War Variant

### ISSUE THREAD

**Issue by tttppp** [zond/godip#27]
This is a two player variant designed to be very balanced. It is a map only variant too, which is useful for getting the generator validated.

I've made a start on this here:
https://github.com/zond/godip/tree/coldWarVariant?files=1

**Comment by zond** [comment]
Nice!

**Comment by tttppp** [comment]
This is getting much closer now. I need to tidy up the branch by removing the "Hundred" artifacts. I also need to add at least one test and fill in the "Cold War" variant description and rules.

The map has a lot of regions in it (about 100 including coasts), and so the map dimensions are big, and the units look a bit small.  I hope it's acceptable on a mobile device.

A couple of images:

The empty map:
![empty svg](https://user-images.githubusercontent.com/7073263/31588929-e911725c-b1f0-11e7-91f7-9253333df428.png)

The map with some (tiny) armies on it (ignore the lack of water colouring here):
![units_army_land svg](https://user-images.githubusercontent.com/7073263/31588932-efa585fe-b1f0-11e7-9540-0a27fcf56ef0.png)

**Comment by zond** [comment]
Looks cool - there will be a lot of zooming and panning :)
