### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rfw** [zond/godip#31]
I'd like to use godip for an implementation of an online adjudicator, but I want to make sure I'm using it under permissible terms: is there a license available for this library? Thanks!

**Comment by zond** [comment]
Do whatever you want with it :)

**Comment by zond** [comment]
But I would love feedback, patches when you find improvements, and info about how you are using it :D

**Comment by rfw** [comment]
Awesome! Could you please put an explicit license grant into the repo? I think code that doesn't have a license is considered all rights reserved instead of free and open source, so adding one might help out the next person who might come around with the same question :)

**Comment by zond** [comment]
OK, done :)
