### ISSUE TITLE
Youngstown Redux Variant

### ISSUE THREAD

**Issue by tttppp** [zond/godip#33]
Implement the Youngstown Redux 10 player variant  from here: http://www.vdiplomacy.com/variants.php?variantID=59

Most of the work for this is done here:
https://github.com/zond/godip/tree/youngstownredux

**Comment by tttppp** [comment]
Still needs variant tests and trying it locally to check the map is ok on an Android device.

**Comment by zond** [comment]
Awesome!

**Comment by tttppp** [comment]
I came across a fun problem while implementing this and I haven't decided how to resolve it yet.  The original game's map shows that Hebei (South Coast) is not connected to Yellow Sea, however the original game definition has a connection:

http://www.vdiplomacy.com/edit.php?variantID=59&mode=all&edit=off&mapsize=small&mapmode=all&terrID=126&terrID=133

I came across this while testing a game where Japan used that connection: http://www.vdiplomacy.com/board.php?gameID=30007

Since the rules don't mention this, I think the original map is correct and the connection should not be there. However the game is fairly balanced with the connection, so maybe it's best to leave it in.  I'll have a think and come back later.

**Comment by zond** [comment]
Tricky problem. But as long as the map looks like the way it's actually connected I guess any option is fine.

**Comment by tttppp** [comment]
I went with the simple option of keeping the map cleaner - i.e. there is no connection (because otherwise there would need to be four regions all connected to each other).

**Comment by zond** [comment]
Sounds good.
