### ISSUE TITLE
Pure Variant

### ISSUE THREAD

**Issue by tttppp** [zond/godip#4]
Implement the Pure variant: http://www.vdiplomacy.com/variants.php?variantID=11

This isn't a particularly fun or popular variant, but it's one step harder than "France vs Austria". It shares the same nations, and some of the same provinces/SCs as classical.

Work in progress is here:
https://github.com/tttppp/godip/tree/PureVariant

**Comment by tttppp** [comment]
The issues I'm getting at the moment are:
```
/home/t/projects/go/src/github.com/zond/diplicity/variants/maps.go:48: variant.Graph.Provinces undefined (type func() "github.com/zond/godip/common".Graph has no field or method Provinces)
/home/t/projects/go/src/github.com/zond/diplicity/variants/maps.go:50: variant.Graph.SC undefined (type func() "github.com/zond/godip/common".Graph has no field or method SC)
```

It seems to be happening even if I use the classical Graph function, rather than PureGraph.

**Comment by zond** [comment]
Did you pull the diplicity repo after I changed how variant graphs are defined?

**Comment by tttppp** [comment]
Ah, I bet I didn't. I pulled the godip report, but probably forgot diplicity. Thanks!

**Comment by tttppp** [comment]
I've made a couple of pull requests for this now (one here and one in diplicity).  I tested that it's possible to start a game, submit some orders and resolve a phase.  I didn't test completing a game.

I also had lots of trouble with cached svg maps. I think the browser caches the ajax call, and updating the version number didn't seem to clear it again. I went through three browsers before I got the map right!  Presumably I can fix it by clearing the browser cache, but it seemed like there should be a better option to allow updating the assets.

**Comment by zond** [comment]
Have you tested that the map rendering (the coloring of provinces and units
etc) works?

**Comment by tttppp** [comment]
Colouring provinces, units and orders are all displayed correctly. I didn't see any pattern for provinces that had actions available (the diagonal stripes). I did include this in the SVG, but I guess it's the responsibility of the client to update the stripy regions depending on how far through an order the user is.

I didn't run the existing tests - we should definitely do that before merging anything. Also I would like to add a complete Pure game as a test. I haven't looked into how that works yet.

**Comment by zond** [comment]
Great - as long as you named and layered the SVG so that the JS can find
province centers (for unit placement) and change color of the provinces it
should be fine I think.

The striping is done by a CSS rule the JS file applies during order input
IIRC.

**Comment by tttppp** [comment]
I'm now able to enter moves through the Android UI and the region highlighting shows up as expected. I'm going to close this.

**Comment by tttppp** [comment]
(The dipl.io UI support is scheduled for 1.0.2, and so isn't available yet)

**Comment by zond** [comment]
@spamguy: How will you solve that? Use the adjudicator supplied maps if you don't have custom support?

**Comment by spamguy** [comment]
@zond Yup, @tttppp opened a ticket for that earlier this week.

**Comment by zond** [comment]
Sounds reasonable
