### ISSUE TITLE
Make retreats to bounced areas invalid

### ISSUE THREAD

**Issue by zond** [zond/godip#45]
I _think_ we allow retreats to bounced areas, but then fail them.

It would be kinder to just treat them as invalid, so that clients using the options input method don't even offer them.

**Comment by tttppp** [comment]
I'm pretty sure we don't suggest retreats to bounced areas.  I'll write a test for this later though.

**Comment by zond** [comment]
Oh!

I wonder why someone asked this in the 2020 game then. But oh well, if we don't suggest it all is well :)

Thanks for creating the 2020 variant by the way, a great achievement! :D

**Comment by tttppp** [comment]
Ha yes - it's been really fun seeing it come to life!

**Comment by tttppp** [comment]
Yep - this was all fine. Tests added here: https://github.com/zond/godip/commit/b54b2d111e252ac101985dfe9651a05a22056d10
