### ISSUE TITLE
Vietnam War variant has invalid province

### ISSUE THREAD

**Issue by spamguy** [zond/godip#54]
One of the provinces in the Vietnam War SVG is named `<path id="path1444">`, which is causing dipl.io to choke when parsing it, since no corresponding province center for that exists. Could this be removed/renamed?

**Comment by zond** [comment]
@tttppp will hopefully take a look at it :)

**Comment by tttppp** [comment]
Thanks for the bug report!  This is now fixed along with a few aesthetic issues with the map.
