### ISSUE TITLE
API Variant not found

### ISSUE THREAD

**Issue by Wulfheart** [zond/godip#56]
Seems quite interesting so far! Unfortunately I have some issues with the API.
The `Readme.md` states `GET http://godip-adjudication.appspot.com/{variant name} lists JSON for a starting map for the named variant. `.
Via ´http://godip-adjudication.appspot.com/classical´ I'm getting ´Variant "classical" not found´.
How can I solve this?
Furthermore I'd love to have some more extensive API docs to see what the API is capable of.

**Comment by zond** [comment]
The variant is named "Classical", i.e. http://godip-adjudication.appspot.com/Classical works fine :)

Unfortunately there isn't much documentation except the code, since most of the effort went into the diplicity server, which is a complete dippy service (and not just an adjudicator).

**Comment by Wulfheart** [comment]
It seems that the routing is case-sensitive. With `classical` it doesn't work.

Thanks for the quick response.
