### ISSUE TITLE
API stateless

### ISSUE THREAD

**Issue by Wulfheart** [zond/godip#57]
Is the API stateless?

My usecase: I'd like to send the current state (not necessarily the start position) to the API combined with the movements and receive a document with the passed movements etc.
Is this possible?

**Comment by zond** [comment]
Then you're in luck, since that is pretty much the only thing this API does :)

If you intend to use it seriously, then tell me so that I can make sure the service runs the latest version with all the latest bugfixes and variants.

**Comment by Wulfheart** [comment]
Thank you again for your quick response.

`POST http://godip-adjudication.appspot.com/{variant name} expects the body to be JSON matching a state previously provided by the corresponding GET URL but with populated orders, and returns the next state JSON.`
I gather that this might be the method you mentioned earlier. However it is uncertain for me how to populate it with data. Is there any example JSON or a file where the input is specified?

**Comment by zond** [comment]
What you get from the initial request (the starting state) is the only example I have, but the code (https://github.com/zond/godip/blob/master/gae/router.go#L22 and https://github.com/zond/godip/blob/master/gae/common.go#L10 mainly) tell you what is needed.

**Comment by Wulfheart** [comment]
I might be making a pull request to group the supply centers respectively the provinces by country.
And I'm intending to use it at least for a prototype of a diplomacy platform.

What is the format for the orders?

**Comment by zond** [comment]
SCs have a country (in some variants) as home SCs, but other than that it shifts over time - and provinces don't really have any country at all (in the sense of affecting the outcome of the rule adjudication), so how do you mean?

Also, how did you intend to group them in the code? Godip has no information about what provinces belongs to what countries, other than variants having home SCs and/or SCs where there are units in the start state.

Order format is defined by the order types, e.g. https://github.com/zond/godip/blob/master/orders/move.go#L253 (for parsing) and https://github.com/zond/godip/blob/master/orders/move.go#L30 (for unparsing), but in general they look like e.g. "bel Move hol".

**Comment by Wulfheart** [comment]
I think I will have to hook in a custom map render. And I will handle the ownership of provinces in my application as the API is stateless (you mentioned it several times).
For prototyping reasons: From which route do I get the adjudicated map?

Do I get you right that the body of the Post request has to be in this (`bel Move hol`) form? Would you mind to provide a very basic example of the post request's body? Is there any syntax reference (even in the code) for the orders? Might it be useful to add a optional json layer for a more convenient input?

Am I able to get the adjacent provinces or would this need a new written API endpoint? If yes, I will make an issue if you would be willing to merge this feature? Same applies for the extra json layer.

**Comment by zond** [comment]
Custom map rendering sounds nice.

As a service to dippy front-ends, godip provides an SVG map for every variant. I would recommend creating some custom transform/rendering of those maps, instead of creating custom maps for every variant (since godip gets new variants regularly, and it's pretty hard to keep a front-end up to date without having to limit the variants you can support due to a lack of maps otherwise).

As I think you mentioned, `POST http://godip-adjudication.appspot.com/{variant name}` expects an incoming state with orders, and provides the resulting state (which I assume you mean by adjudicated map).

The body of the `POST` should be in the form that you got from the initial `GET` (that provided the example start state), e.g.

```
$ curl -X POST --data '{"Season":"Spring","Year":1901,"Type":"Movement","Units":{"ank":{"Type":"Fleet","Nation":"Turkey"},"ber":{"Type":"Army","Nation":"Germany"},"bre":{"Type":"Fleet","Nation":"France"},"bud":{"Type":"Army","Nation":"Austria"},"con":{"Type":"Army","Nation":"Turkey"},"edi":{"Type":"Fleet","Nation":"England"},"kie":{"Type":"Fleet","Nation":"Germany"},"lon":{"Type":"Fleet","Nation":"England"},"lvp":{"Type":"Army","Nation":"England"},"mar":{"Type":"Army","Nation":"France"},"mos":{"Type":"Army","Nation":"Russia"},"mun":{"Type":"Army","Nation":"Germany"},"nap":{"Type":"Fleet","Nation":"Italy"},"par":{"Type":"Army","Nation":"France"},"rom":{"Type":"Army","Nation":"Italy"},"sev":{"Type":"Fleet","Nation":"Russia"},"smy":{"Type":"Army","Nation":"Turkey"},"stp/sc":{"Type":"Fleet","Nation":"Russia"},"tri":{"Type":"Fleet","Nation":"Austria"},"ven":{"Type":"Army","Nation":"Italy"},"vie":{"Type":"Army","Nation":"Austria"},"war":{"Type":"Army","Nation":"Russia"}},"Orders":{},"SupplyCenters":{"ank":"Turkey","ber":"Germany","bre":"France","bud":"Austria","con":"Turkey","edi":"England","kie":"Germany","lon":"England","lvp":"England","mar":"France","mos":"Russia","mun":"Germany","nap":"Italy","par":"France","rom":"Italy","sev":"Russia","smy":"Turkey","stp":"Russia","tri":"Austria","ven":"Italy","vie":"Austria","war":"Russia"},"Dislodgeds":{},"Dislodgers":{},"Bounces":{},"Resolutions":{},"Orders":{"England":{"lon":["Move","eng"]}}}' http://godip-adjudication.appspot.com/Classical
{"Season":"Spring","Year":1901,"Type":"Retreat","Units":{"ank":{"Type":"Fleet","Nation":"Turkey"},"ber":{"Type":"Army","Nation":"Germany"},"bre":{"Type":"Fleet","Nation":"France"},"bud":{"Type":"Army","Nation":"Austria"},"con":{"Type":"Army","Nation":"Turkey"},"edi":{"Type":"Fleet","Nation":"England"},"eng":{"Type":"Fleet","Nation":"England"},"kie":{"Type":"Fleet","Nation":"Germany"},"lvp":{"Type":"Army","Nation":"England"},"mar":{"Type":"Army","Nation":"France"},"mos":{"Type":"Army","Nation":"Russia"},"mun":{"Type":"Army","Nation":"Germany"},"nap":{"Type":"Fleet","Nation":"Italy"},"par":{"Type":"Army","Nation":"France"},"rom":{"Type":"Army","Nation":"Italy"},"sev":{"Type":"Fleet","Nation":"Russia"},"smy":{"Type":"Army","Nation":"Turkey"},"stp/sc":{"Type":"Fleet","Nation":"Russia"},"tri":{"Type":"Fleet","Nation":"Austria"},"ven":{"Type":"Army","Nation":"Italy"},"vie":{"Type":"Army","Nation":"Austria"},"war":{"Type":"Army","Nation":"Russia"}},"Orders":{},"SupplyCenters":{"ank":"Turkey","ber":"Germany","bre":"France","bud":"Austria","con":"Turkey","edi":"England","kie":"Germany","lon":"England","lvp":"England","mar":"France","mos":"Russia","mun":"Germany","nap":"Italy","par":"France","rom":"Italy","sev":"Russia","smy":"Turkey","stp":"Russia","tri":"Austria","ven":"Italy","vie":"Austria","war":"Russia"},"Dislodgeds":{},"Dislodgers":{},"Bounces":{},"Resolutions":{"ank":"OK","ber":"OK","bre":"OK","bud":"OK","con":"OK","edi":"OK","kie":"OK","lon":"OK","lvp":"OK","mar":"OK","mos":"OK","mun":"OK","nap":"OK","par":"OK","rom":"OK","sev":"OK","smy":"OK","stp/sc":"OK","tri":"OK","ven":"OK","vie":"OK","war":"OK"}}
```

(I also added this example to the README for godip)

The syntax reference is in https://github.com/zond/godip/blob/master/orders/move.go#L253 (for parsing) and https://github.com/zond/godip/blob/master/orders/move.go#L30 (for unparsing) - and similar for all other orders - as I wrote above.

Adjacency map is available in the code but requires an addition to the API, I would recommend building adding e.g. `http://godip-adjudication.appspot.com/{variant name}/graph` that returns a JSON-serialized version of the graph for the variant.

What do you mean with extra JSON layer?

**Comment by Wulfheart** [comment]
Again thank you for your extensive help.

> What do you mean with extra JSON layer?
I thougt the body would consist of the internal order syntax not the json one.

**Comment by zond** [comment]
It's the same syntax, or rather, the JSON just contains the split order strings as JSON arrays.

You're welcome, I'm happy someone wants to use it :)
