### ISSUE TITLE
Custom map rendering

### ISSUE THREAD

**Issue by Wulfheart** [zond/godip#59]
>Custom map rendering sounds nice.
>
>As a service to dippy front-ends, godip provides an SVG map for every variant. I would recommend creating some custom transform/rendering of those maps, instead of creating custom maps for every variant (since godip gets new variants regularly, and it's pretty hard to keep a front-end up to date without having to limit the variants you can support due to a lack of maps otherwise).

_Originally posted by @zond in https://github.com/zond/godip/issues/57#issuecomment-529349467_

Some thoughts therefore:
1. Which part of the program is responsible for rendering the map?
2. Some existing diplomacy platform (e.g. webdiplomacy and it derivates) are coloring the sphere of influence, meaning that every province is treated like an supply center in regarding ownership with no further effects. Is it possible to implement this? E.g. by extending the post data with an ownership property so that province ownership is also adjudicated.
3. I think that it would be practical to have a seperate render package in the project with multiple renderers?

**Comment by zond** [comment]
1. godip doesn't render, it provides the map for reference. E.g. https://github.com/zond/android-diplicity renders the map using the SVG provided by godip.

2. What you are talking about has no relationship to the adjudication, and is not provided by godip. It would be easy to provide something like that in the game server, as long as you have a way to figure out what it means to own a non SC province.

3. See 1 :)

**Comment by Wulfheart** [comment]
Sorry, I misunderstood the message. In this case I will go with my own renderer as this isn't the scope of this project.
