### ISSUE TITLE
Adjacency mapping endpoint

### ISSUE THREAD

**Issue by Wulfheart** [zond/godip#60]
>Adjacency map is available in the code but requires an addition to the API, I would recommend adding e.g. `http://godip-adjudication.appspot.com/{variant name}/graph` that returns a JSON-serialized version of the graph for the variant.

_Originally posted by @zond in https://github.com/zond/godip/issues/57#issuecomment-529349467_

**Comment by tttppp** [comment]
The adjacency may change throughout the game, for example some variants have frozen/thawed regions that change with the season. In other variants the adjacency depends on the nation or occupation of provinces. (Note none currently implemented).

What is the aim of this endpoint?

**Comment by tttppp** [comment]
Just a note that this is available from Diplicity, but not from the godip-adjudication endpoint.

https://diplicity-engine.appspot.com/Variants

**Comment by Wulfheart** [comment]
I'd like to have a list of possible orders for a given unit. Is this possible?

**Comment by zond** [comment]
Yes, if you explore the API server (https://diplicity-engine.appspot.com/) you'll find that you can navigate to e.g. 'my-started-games', and then go into a game, and list its phases, and then the newest phase has another link called 'options'.

The final URL looks like e.g. https://diplicity-engine.appspot.com/Game/ahJzfmRpcGxpY2l0eS1lbmdpbmVyEQsSBEdhbWUYgICAgICumQoM/Phase/3/Options and it returns a JSON struct containing all possible orders for the logged in user for that particular game.

There is currently no way to get possible orders for other players, or for _only_ a particular unit.

**Comment by Wulfheart** [comment]
Would you be open for an extra endpoint? I’d contribute it.

**Comment by zond** [comment]
Probably, what did you have in mind? :)

**Comment by Wulfheart** [comment]
I need an overview of all possible orders of every unit. I guess I will go to the diplicity repo and get the code from there. ;-)

**Comment by zond** [comment]
I'd just go through all units in the phase struct, and ask for options for each of them.

**Comment by Wulfheart** [comment]
In godip or diplicity?

**Comment by zond** [comment]
I don't know your situation, but if you are only using godip the answer is simple. If you are using diplicity then you probably need to add another endpoint, and the code of that endpoint would do what I suggested. If you want to contribute upstream you'd probably do something like what game/phase.go does when it loads options, i.e. check if the cached+zipped options for the player are populated (they take a while to calculate, sometimes ~1 second), and then merge and return them, possibly after populating them.

**Comment by Wulfheart** [comment]
I'm only using godip. I tried using Diplicity for the project but it is heavily based on Google and the users of the platform I'm developing for have some prejudices about the usage of google. Therefore I'm building an API which is only responsible for adjudicating the games.

**Comment by zond** [comment]
Ah, alright. Well, if you are using the adjudication service that only runs godip, then you cab always add such an endpoint to it. Otherwise I guess you just iterate over all units and ask for options forneach of them.

What platform are you going to use it in, if I may ask?

**Comment by Wulfheart** [comment]
https://diplomacy-network.com - a german fork of webdiplomacy

It is going to be a redevelopment.

**Comment by zond** [comment]
I see.

Have you considered adding the features you're missing to diplicity, and merging the communities? The Google account requirement could be changed to a selection of authentication mechanisms if you don't like it.

Or maybe you want a German speaking service?

**Comment by Wulfheart** [comment]
The hosting by Google is a problem per se. There are legal requirements regarding users from the European Union. The data from users from the EU need to be stored in the EU for example.

**Comment by zond** [comment]
Oh, that's not true. Do you think gmail only stores data about europeans in europe?

**Comment by Wulfheart** [comment]
With the latest case law, including Schrems II, it may well become a problem. Admittedly, it is not yet mandatory, but there are strong prejudices against Google, especially in Germany. 

I would be willing to participate in Diplicity. My ideas would be the following:
- Introduction of a SQL database (e.g. use of ORMs like [ent](https://github.com/facebook/ent))
- Definition of API interfaces via OpenAPI

**Comment by zond** [comment]
Well, one can't (easily) fight opinion :/

Since all of diplicity today is based on using App Engine and it's dDatastore to stay simple to deploy and scale, changing persistence solution is decidedly nontrivial. However, there are non-Google solutions that are API-compatible with App Engine, such as https://github.com/AppScale/gts that may provide the freedom-from-Google that you need?

What is OpenAPI, and what are the benefits of defining API interfaces via it?

**Comment by Wulfheart** [comment]
Using something hyperscalable like App Engine is too much in my opinion. Playing diplomacy is a niche on the internet and there are not many players. 
App Engine in its lowest config costs around 36$ per month. Am I correct about this?

OpenAPI a standardized way to describe APIs. This allows the automatic generation of client and server implementations (if needed) and adds also a documentation to the API which can be accessed as a whole. [Example](https://petstore3.swagger.io/)

**Comment by zond** [comment]
An App Engine instance that heavily uses memcache can be almost free even when seeing reasonable use. I have been running an App Engine instance for a customer for < $1/month for many years.

Diplicity doesn't use memcache, I'm currently more lazy than cheap, and it costs ~$15/month.

The reason I'm using App Engine isn't primarily due to scaling (even if it's _a_ reason - Droidippy finally died due to scalability issues), but ease of deployment and provisioning.

I'm guessing it would be fairly easy to add OpenAPI support to diplicity - it already has a self describing/documenting system (see https://diplicity-engine.appspot.com), and a Java client generator (see the java directory in the source).

**Comment by Wulfheart** [comment]
Guess I will currently not join diplicity development. I'm lacking the experience in Memcache. 
However, I am going to use godip and wrap an API for the purpose around. 
Thanks for your efforts. I think this project is great. Especially because it is written in Go.

**Comment by zond** [comment]
You could (as I said before) run diplicity in an open source API compatible App Engine alternative, then you wouldn't have to implement any memcache stuff, could use diplicity as is, and could host it on your own server without Google Cloud costs or privacy issues.

And auto generating OpenAPI from the current server is likely not very hard either.

What are the blockers for that route? Sorry for being persistent, but even if it'd be impossible to merge the player communities it would be awesome to join efforts on the development.

**Comment by Wulfheart** [comment]
For me the fixation on App Engine or compatible APIs is a major dealbreaker. Thus I am too much fixated on one API. In my opinion it is not that hard spinnung up a SQL Database and deploy a go application.

**Comment by zond** [comment]
What I'm fixated on isn't App Engine, but not rewriting the entire application while still increasing the number of active developers :)

If course spinning up an application isn't a lot of work, but writing a complete application with all the functionality you want is a bit of work. And there

**Comment by Wulfheart** [comment]
I appreciate your point. I'm just saying that it is unfortunately not working for me.

**Comment by zond** [comment]
Which of my points? I edited that reply a lot of times :D

**Comment by Wulfheart** [comment]
Oh. I can't remember right now.

> All that said: If you managed to create a persistence adapter layer that made it work with either an SQL or the current hosting solution I'd be totally open to that.
At the end of the I would be impleting a total App Engine alternative. Although this is an interesting project it is currently out of my scope.

**Comment by zond** [comment]
> > All that said: If you managed to create a persistence adapter layer that made it work with either an SQL or the current hosting solution I'd be totally open to that.
> 
> At the end of the I would be impleting a total App Engine alternative. Although this is an interesting project it is currently out of my scope.

Porting an app to SQL and porting it to an adapter supporting both SQL and X are probably not that far apart in work hours, though.

But I think we've spent too much time discussing this - I'm almost as happy about you using and potentially contributing to godip as diplicity, so let's focus on that :D

**Comment by Wulfheart** [comment]
Ok. I have some ideas. I will open separate issues for this.
