### ISSUE TITLE
Starting development server

### ISSUE THREAD

**Issue by Wulfheart** [zond/godip#61]
How can I start the development server locally in go?
The `go run router.go` command returns `go run: cannot run non-main package` and it seems unpractical to me to always upload it to google cloud to test it. Do you have any advice?

**Comment by zond** [comment]
Godip is essentially library, and the server is really just an afterthought.

The server runs in a free tier Google App Engine, and to run it locally you need to follow the instructions at https://cloud.google.com/appengine/docs/standard/python/tools/using-local-server in the `gae` directory.

I haven't done it in ages, so I hope it still works - tell me if it doesn't.

**Comment by Wulfheart** [comment]
> Running locally
>
>To test your application's functionality before deploying, run your application in your local environment with the development tools that you usually use. For example, the go run command.

As it is golang.

**Comment by tttppp** [comment]
I'm not sure I've ever used the files in the gae directory. To run locally I use the app directory in Diplicity.

**Comment by Wulfheart** [comment]
Still not able to open the dev server. 
As I'm not working on it right now I will close this issue. Feel free to reopen.
