### ISSUE TITLE
Conquering non-SC territories

### ISSUE THREAD

**Issue by JorenC** [zond/godip#67]
To make the map feel much more like you're achieving something, we talked about implementing the possibility to conquer (colour) territories that are not SCs.

I'm writing the rules here in an issue, for when tttppp has some time ;)
In the future, I'll see if I can add some example maps here.
- Risk: 'newbie' players would assume there is value in having a non-SC state which would be coloured in their colour, e.g. Piedmonte, losing focus of SCs (but that is just a deception trick addd to the game, and since the territories will not change unless SCs are captured, it's quickly learned).
- Risk: harder to distinguish where armies are if they're all the same colour of their background (might need a thicker border).
- Benefit: Really feels like you're conquering a territory, sense of achievement.

A suggested logic would be:
1. When an SC get's captured, re-evaluate all adjacent non-SC territories.
2. For each evaluated non-SC territory, check the surrounding SC territory owners
- IF different owners, colour the non-SC territory neutral (contested territory)
- IF all the same owner (or neutral), colour the non-SC territory to that owner colour (buffer state)

3. At the start of the game, an XML file would define the colour the default provinces (otherwise, Burgundy & Piedmont would be coloured neutral). If that XML is not provided in the variant, either apply the default logic as above.

**Comment by zond** [comment]
Considering we have the connective graph for all variants in the .../Variant/{variant_name} API endpoint, we could even implement it in the client if we wanted.

**Comment by Wulfheart** [comment]
@JorenC I really like this idea and would definitely love seeing it implemented.

**Comment by JorenC** [comment]
@Wulfheart I've just implemented it in Dipact (branch "NonSCs"). It'll take a while before Martin gets around to implementing my buggy code, and I've still got some base work to do in setting up the 'startingprovs' logic/xmls, but it's getting there (hopefully soon!)

**Comment by Wulfheart** [comment]
@JorenC what is dipact? Is there a repository?

**Comment by JorenC** [comment]
Hi Alex,

Dipact is the repo for the Android and web client for Diplicity.
Repo is zond/dipact

(Dipact -> Diplicity / React).

Cheers,

J
