### ISSUE TITLE
Validating incorrect ordres.

### ISSUE THREAD

**Issue by JorenC** [zond/godip#88]
![image](https://user-images.githubusercontent.com/7293081/83460515-e1cab880-a466-11ea-8895-cf9d5e0e160f.png)

The above should not be possible.
According to the rules, a support order ONLY succeeds if the receiving unit has the same order. 
So, a support hold order to a unit moving away from it's province would fail. 

This is tricky to understand; alternatively, if I support the unit (and it's move is bounced, for example), it _might_ succeed - depending on interpretation of the edge case of the rules. 

I had to warn my friends that did this in my games multiple times, and had to look up the rules. 

- 

Ideally, we want this order of Moscow to be give "ErrNotCompliant" or something. In this situation it should fail because the receiving unit is not following the support exactly. Even though it did NOT get attacked, it should still fail, because the support order was invalid - hence the warning (which is actually correct!).

**Comment by JorenC** [comment]
Also, IF you're fixing that, could you also make this order in human language be "Moscow support Lenningrad **hold**?

**Comment by zond** [comment]
I have pushed a new version of adjudicator and server that will fail those support orders with ErrInvalidSupporteeOrder. I also updated dipact to add a " hold" at the end of support orders for hold.
